spring.application.name=project0
spring.datasource.url=jdbc:mysql://localhost:3306/project0
spring.datasource.username=root
spring.datasource.password=newpassword
#spring.datasource.password=mg2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=lqNLWkSrx3TUaXyqrG8eqTP4Te7Q5f9sbI18tpgS0gY=

#Judge0 Configuration
judge0.api.url=http://20.244.28.213:2358/submissions/batch
judge0.api.callbackUrl=https://voucher-paralyses-aflutter.ngrok-free.dev/api/judge/submission
judge.api.run.callbackUrl=https://voucher-paralyses-aflutter.ngrok-free.dev/api/judge/run
#judge0.api.url=http://localhost:2358/submissions?base64_encoded=false&wait=true
#judge0.api.key=3b22b2fb41msh6c43fc485785571p1a91dbjsn8f8e2c6858f0
#judge0.api.host=judge0-ce.p.rapidapi.com
spring.datasource.hikari.maximum-pool-size=30

# ThreadPool Configuration
pool.size.core=4
pool.size.max=8
pool.uptime=10000